(*             v1                  *)
(* very simple ocaml language      *)
expr ::= constant                                  # ConstantExpr
| '(' expr ')'                                     # ParenExpr
| expr { argument }+                               # CallExpr
| expr infix-op expr                               # BinaryExpr
| 'if' expr 'then' expr [ 'else' expr ]            # CondExpr
| expr ';' expr                                    # SeqExpr
| 'let' [ 'rec' ] let-binding                      # LetBindingExpr
| object-expr                                      # ObjectExpr

eof ::= ';;' | EOF                                 # tok_eof

constant ::= integer-literal                       # tok_int
| 'false'                                          # tok_false
| 'true'                                           # tok_true
| '()'                                             # tok_unit

argument ::= expr                                  # Argument

integer-literal ::= [ '-' ]( digit ){ digit | '_' }

digit ::= '0-9'

infix-op ::= 
|'+'                                                # AddOp
| '-'                                               # SubOp
| '*'                                               # MulOp
| '/'                                               # DivOp
| '='                                               # EqOp
| '<'                                               # LtOp
| '>'                                               # GtOp
| '<='                                              # LeOp
| '>='                                              # GeOp
| '<>'                                              # NeOp

let-binding ::= pattern '=' expr                   # LetPatternBinding
| value-name { parameter } '=' expr                # LetFunctionBinding 

parameter ::= pattern                              # Parameter

pattern ::= value-name                             # ValueNamePattern
| '_'                                              # DefaultPattern
| constant                                         # ConstantPattern
| pattern 'as' value-name                          # AsPattern
| '(' pattern ')'                                  # ParenPattern
| pattern '|' pattern                              # UnionPattern


value-name ::= lowercase-ident                     # LowercaseIdent

lowercase-ident ::= ( 'a-z' | '_' ){ letter | digit | '_' | '\'' }

object-expr ::= lowercase-ident                    # ObjectExpr